[project]
name = "zm09"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typer>=0.16.0",
]

[project.scripts]
zm09 = "zm09.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
